### PR TITLE
perf: Use pickle instead of json

### PR DESCRIPTION
**Pull request by jpmckinney**
After #74, it became apparent that a lot of time was spent serializing the state file. I changed the code to use pickle, and it is much faster. This also means we can probably delete some code (`DataPreprocessor.restore`, `Table.dump`, etc.).

### CODE REVIEW

**Comment by jpmckinney** [comment]
I haven't updated the tests, but the test for loading a state file is now failing.

**Comment by yshalenyk** [comment]
@VDigitall please check this out, this might require to change spoonbill-web a bit

**Comment by yshalenyk** [comment]
@jpmckinney changed a bit to minimize work on web

**Comment by jpmckinney** [comment]
Looks good - thanks :)

**Pull request merged**
